### ISSUE TITLE
`sup`, `sub` elements

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/hast-util-to-mdast#24]
[`sup`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup), [`sub`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sub)

We can either try something with unicode superscript and -subscript, but I think that goes to far.
Ignoring is probably better.

**Comment by Mr0grog** [comment]
I know this issue is *long* since closed, but I think it would be nice to output HTML tags here by default (I agree unicode would be going too far). Even though it’s kind of ugly, I think it’s better to be reasonably faithful to the input markup than to have the formatting disappear entirely, since the superscript/subscript can be pretty meaningful in a lot of cases.

That said, I appreciate that the `all()` function and the `handlers` option make supporting it in a third party tool really simple. 😄  (I recently had a feature request for this in [google-docs-to-markdown](https://github.com/Mr0grog/google-docs-to-markdown/pull/34).)

**Comment by wooorm** [comment]
Hey! You can do what you want, see https://github.com/syntax-tree/hast-util-to-mdast#example-keeping-some-html.

100% HTML or 0% HTML is a scale. This project is at 0% (only “normal” markdown). There’s a) no good reason to move that scale to 1% (only one or two elements), b) no good reason for those tags to be `sub`, `sup`, c) not every user agrees that `sub`, `sup` should default to HTML representations. So I don’t think it’s wise to change it.
